version: '3.4'
services:
  bandnames_server:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: bandnames_server
    restart: always
    ports:
      - 3001:3001
